name: Deploy til dev via workflow dispatch og prod via push til master
on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md'
  workflow_dispatch:

env:
  IMAGE_BASE: ghcr.io/${{ github.repository }}

jobs:
  deploy-docker-image:
    name: Deploy Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Sette opp Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Installere dependencies
        run: npm install
      - name: Kjøre enhetstester
        run: npm test
      - name: Kjøre bygg
        run: npm run build
      - name: Sette versjon
        run: |
          echo "MAJOR_VERSION=$(npm run majorVersion --silent)" >> $GITHUB_ENV
      - name: Sette tag
        run: |
          echo "TAG=$(date "+%Y.%m.%d-%m")-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Sette miljøvariabler
        run: |
          echo "IMAGE=${IMAGE_BASE}:${TAG}" >> $GITHUB_ENV
          echo "LATEST=${IMAGE_BASE}:latest" >> $GITHUB_ENV
          echo "CSS_HASH=$(shasum -b -a 384 build/${MAJOR_VERSION}/styles.css | awk '{ print $1 }' | xxd -r -p | base64)" >> $GITHUB_ENV
          echo "JS_HASH=$(shasum -b -a 384 build/${MAJOR_VERSION}/app.js | awk '{ print $1 }' | xxd -r -p | base64)" >> $GITHUB_ENV
      - name: Bygg og laste opp docker-image
        run: |
          docker build --pull --tag ${IMAGE} --tag ${LATEST} .
          echo ${GITHUB_TOKEN} | docker login --username ${GITHUB_REPOSITORY} --password-stdin ghcr.io
          docker push ${IMAGE_BASE} -a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/naiserator.yml
          VARS: nais/dev-gcp.json
      - name: Deploy til prod-gcp
        if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'ci skip')
        uses: nais/deploy/actions/deploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/naiserator.yml
          VARS: nais/prod-gcp.json
      - name: Create Release
        id: create_release
        if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'ci skip')
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: ${{ env.TAG }}
          body: |
            For JS, add this to your app:
            ```
            <script
              type="text/javascript"
              src="https://omsorgsdager-frontend.dev.intern.nav.no/${{ env.MAJOR_VERSION }}/app.js"
              integrity="sha384-${{ env.JS_HASH }}"
              crossorigin="anonymous"
            ></script>
            ```

            For CSS, add this to the `<head>` of your app:
            ```
            <link
              rel="stylesheet"
              href="https://omsorgsdager-frontend.dev.intern.nav.no/${{ env.MAJOR_VERSION }}/styles.css"
              integrity="sha384-${{ env.CSS_HASH }}"
              crossorigin="anonymous"
            >
            ```
          draft: false
          prerelease: false
