name: Bygg og deploy til Dev
on: [workflow_dispatch]
env:
  IMAGE_BASE: ghcr.io/${{ github.repository }}
jobs:
  deploy-docker-image:
    name: Bygg og deploy til Dev
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Sette opp Node
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 12.x
      - name: Installere dependencies
        run: npm install
      - name: Kjøre enhetstester
        run: npm test
      - name: Sette tag
        run: |
          echo "TAG=$(date "+%Y.%m.%d-%m")-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Sette miljøvariabler
        run: |
          echo "IMAGE=${IMAGE_BASE}:${TAG}" >> $GITHUB_ENV
          echo "LATEST=${IMAGE_BASE}:latest" >> $GITHUB_ENV
      - name: Bygg og laste opp docker-image
        run: |
          docker build --pull --tag ${IMAGE} --tag ${LATEST} .
          echo ${GITHUB_TOKEN} | docker login --username ${GITHUB_REPOSITORY} --password-stdin ghcr.io
          docker push -a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/naiserator.yml
          VARS: nais/dev-gcp.json
      - name: Set changelog
        run: |
          text="$(git --no-pager log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%h %s")"
          text="${text//$'\n'/\\n}"
          echo "CHANGELOG=$text" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: d-${{ env.TAG }}
          release_name: DEV - ${{ env.TAG }}
          body: |
            For JS, add this to your app:
            ```
            <script
              type="text/javascript"
              src="https://omsorgsdager-frontend.dev.intern.nav.no/dev/app.js"
              crossorigin="anonymous"
            ></script>
            ```
            For CSS, add this to the `<head>` of your app:
            ```
            <link
              rel="stylesheet"
              href="https://omsorgsdager-frontend.dev.intern.nav.no/dev/styles.css"
              crossorigin="anonymous"
            >
            ```
            **Changes in this Release**
            ${{ env.CHANGELOG }}
          draft: false
          prerelease: false