name: Bygg og deploy til Prod
on:
  push:
    paths:
      - 'build/prod/**'
    branches:
      - main
  workflow_dispatch:
env:
  IMAGE_BASE: ghcr.io/${{ github.repository }}
jobs:
  deploy-docker-image:
    name: Bygg og deploy til Prod
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Sette opp Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 16.x
      - name: Installere dependencies
        run: npm install
      - name: Kjøre enhetstester
        run: npm test
      - name: Sette tag
        run: |
          echo "TAG=$(date "+%Y.%m.%d-%m")-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      - name: Sette miljøvariabler
        run: |
          echo "IMAGE=${IMAGE_BASE}:${TAG}" >> $GITHUB_ENV
          echo "LATEST=${IMAGE_BASE}:latest" >> $GITHUB_ENV
      - name: Bygg og laste opp docker-image
        run: |
          docker build --pull --tag ${IMAGE} --tag ${LATEST} .
          echo ${GITHUB_TOKEN} | docker login --username ${GITHUB_REPOSITORY} --password-stdin ghcr.io
          docker push ${IMAGE_BASE} -a
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy til prod-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/naiserator.yml
          VARS: nais/prod-gcp.json
      - name: Set changelog
        run: |
          text="$(git --no-pager log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%h %s")"
          text="${text//$'\n'/\\n}"
          echo "CHANGELOG=$text" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: p-${{ env.TAG }}
          release_name: PROD - ${{ env.TAG }}
          body: |
            For JS, add this to your app:
            ```
            <script
              type="text/javascript"
              src="https://omsorgsdager-frontend.dev.intern.nav.no/prod/app.js"
              crossorigin="anonymous"
            ></script>
            ```
            For CSS, add this to the `<head>` of your app:
            ```
            <link
              rel="stylesheet"
              href="https://omsorgsdager-frontend.dev.intern.nav.no/prod/styles.css"
              crossorigin="anonymous"
            >
            ```
            **Changes in this Release**
            ${{ env.CHANGELOG }}
          draft: false
          prerelease: false
