name: Validere pull request
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  valid-pull-request:
    name: Validere pull request
    runs-on: ubuntu-latest
    steps:
      - name: Hente kode
        uses: actions/checkout@v2
      - name: Sette opp Node
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 12.x
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Installere avhengigheter
        run: yarn install --ignore-optional --no-progress --frozen-lockfile
      - name: Test
        run: yarn test
      - name: Lint
        run: yarn lint && yarn lint:css